server.port=8081

logging.level.root=INFO
#logging.file.name=route
#apikeydatabase
database.apikey=
#turso database url
database.url=
#configuracion de jwt
rucoy.api.secret=e7dcbd52-e4b1-44ce-afcd-36b5d3be8ea8
rucoy.api.pathToken=/auth/**
rucoy.api.paths=/api/v1/**